//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/Scripts/New Player Control.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewPlayerScript : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewPlayerScript()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Player Control"",
    ""maps"": [
        {
            ""name"": ""Land"",
            ""id"": ""c3434c1a-0856-4791-b946-996d2bbee7f5"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""282e9c2b-b21b-402a-9dc7-d158a910f36e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c7c3773f-8cbf-405f-9188-ee097a494d6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""vert"",
                    ""type"": ""Button"",
                    ""id"": ""328b6661-5218-45aa-aabf-d807c7fd93ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dash"",
                    ""type"": ""Button"",
                    ""id"": ""e8637f07-e5ca-4c5f-ad11-c4fb029aec3e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""atk"",
                    ""type"": ""Button"",
                    ""id"": ""a785d7e2-e467-478f-8a18-2776dc48e79b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""cure"",
                    ""type"": ""Button"",
                    ""id"": ""dff7a015-9e75-496f-ba29-2c8d478af372"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""whell"",
                    ""type"": ""Button"",
                    ""id"": ""04a91c7a-eea7-460d-991f-ea41c0d3561b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold,Press,Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""spell"",
                    ""type"": ""Button"",
                    ""id"": ""b2a41cf5-5814-4f8c-a1f0-dea3390670f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ulti"",
                    ""type"": ""Button"",
                    ""id"": ""b5bc1ea3-6612-41e5-bc55-fc85199a416c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""parry"",
                    ""type"": ""Button"",
                    ""id"": ""73830e57-f19b-43b2-a5eb-8a61f81aa879"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""chargeAtk"",
                    ""type"": ""Button"",
                    ""id"": ""d6163a6a-958a-4243-bceb-00e88bb7c184"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""interact"",
                    ""type"": ""Button"",
                    ""id"": ""3850f856-6451-4960-aa8f-1351149b8404"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dialogue"",
                    ""type"": ""Button"",
                    ""id"": ""6735f5c9-333e-4980-81a4-f95f4845c303"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""start"",
                    ""type"": ""Button"",
                    ""id"": ""7a601a5d-10b7-4940-a000-13def7a3b780"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""select"",
                    ""type"": ""Button"",
                    ""id"": ""78925f14-0b3a-45fe-9ac2-8df3d83fec01"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Sideways"",
                    ""id"": ""4844ae6b-a9d8-4008-9bf9-762e9418d9ef"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3982f90a-87c3-459f-970d-b12067b4ac5b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0d9429a2-e5b2-4605-b9a0-1a8532dd402a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Sideways dpad"",
                    ""id"": ""fcb4b458-ca47-48e1-9243-fbdb5db5d941"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4fed4c21-9a17-46a3-a9ff-842387a7add2"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9b11ab49-5207-49e7-8dde-0861d68df455"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Sideways joystick"",
                    ""id"": ""6d2ab07f-e1e8-4e46-a418-950f33991176"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""445f8729-012a-4619-9245-824906945d82"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""fb02a755-67f4-4742-b7b0-3a0582240014"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""445c1aac-925f-4fff-85b2-e4ba3353f82a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4090875-47e5-4976-92bf-e1cdeaedc38b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""vertical"",
                    ""id"": ""c883099e-20d4-4878-99a0-1ec47c68c648"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d2506d4c-3d51-4765-a7e1-d35fbc906469"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""da704fde-0422-4c42-bb6f-bf533be61627"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""vertical dpad"",
                    ""id"": ""36466bbc-0d1d-428c-ac46-9935e579240f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""de8b6648-d111-4594-a2e4-92ca8cbf8179"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""8c1f919f-c2b0-48ac-97d8-fc2b726fd8fb"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""vertical joystuck"",
                    ""id"": ""5667fc9d-fdad-4bad-b5e1-f0106b04514a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e3c2120f-ca44-4cfe-a627-b97de25c7793"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""c62d609c-349a-4c20-a3f2-91958221700a"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""vert"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""70187dfc-eb83-4c92-8a62-bf36a803c1e6"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""066a0ecc-a586-4735-86b3-5c55eb873374"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd19b28e-da4c-4631-92bd-e8a66be03d83"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""atk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e5c125a-e4e2-42b7-8593-4b6cc73c3392"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""atk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25256e0c-1b41-4d30-8431-123ef3643b00"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cure"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f241a00-7bb0-442d-ba95-c8c038eff3aa"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cure"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fbdc9fa-a8e0-43fe-8ca3-48ccb9f2dd12"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""whell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34223463-d4ed-4fd5-b3d9-aba6c4e8bbb4"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""whell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b11bb1f-05e0-4289-9a61-ac6c850bb68a"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85d38b09-8d16-460e-a65e-0a5029e565d1"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""5a3c1d2f-b1a6-428f-8c40-cba013aa59d2"",
                    ""path"": ""OneModifier"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ulti"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4f3fe073-6dc8-4a05-b369-f7a4679a3fea"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ulti"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""10fffe2e-b522-45e6-a466-2a7c0af4642c"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ulti"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""09339d6c-6b20-4aca-9dc5-7ead1e46a9e4"",
                    ""path"": ""OneModifier"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ulti"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""239581dc-6776-4ab6-b324-ec458118741d"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ulti"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0e3a0e09-6fbc-4a42-80e9-e24d854e8dcb"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ulti"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c17e5041-f04c-4d58-976e-9fbe77bfa4c9"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a28d77e-58df-4cef-88b0-7f73a40a6948"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02ede304-07dd-4f02-92d4-ca513fc6b1d8"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""chargeAtk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a17f58e-dcd4-4ab0-a905-0d2461ae4db1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""chargeAtk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb832a95-51f0-4ca6-b53c-a6f99f6758ef"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a58db43-0211-4d91-8719-70e8a5025d5a"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""892a35d6-b6db-4523-bfe1-0c209d82b9db"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""ab3fc0eb-710b-49cd-8ab8-acce083a829a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dialogue"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6ab29b2d-9495-42a9-8785-100c223662af"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""99c86e72-4f59-4869-8150-070eba2e719d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""481a2796-b50b-417b-abf0-77ed8bd99c6b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dialogue"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""629f2e58-ffa1-4eb9-938f-eb2cd11ff208"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f3f79413-c8eb-4e38-abd0-164aad930a29"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fc364ff9-4e88-4034-b222-af36dc2977a4"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa4f0061-9a98-4e25-974c-59ea39533b79"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1e3dde5-bc56-4ebf-a026-b7a57ee87e4c"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad35c515-4d0f-430e-a09e-793ffbf8f8a9"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Land
        m_Land = asset.FindActionMap("Land", throwIfNotFound: true);
        m_Land_move = m_Land.FindAction("move", throwIfNotFound: true);
        m_Land_Jump = m_Land.FindAction("Jump", throwIfNotFound: true);
        m_Land_vert = m_Land.FindAction("vert", throwIfNotFound: true);
        m_Land_dash = m_Land.FindAction("dash", throwIfNotFound: true);
        m_Land_atk = m_Land.FindAction("atk", throwIfNotFound: true);
        m_Land_cure = m_Land.FindAction("cure", throwIfNotFound: true);
        m_Land_whell = m_Land.FindAction("whell", throwIfNotFound: true);
        m_Land_spell = m_Land.FindAction("spell", throwIfNotFound: true);
        m_Land_ulti = m_Land.FindAction("ulti", throwIfNotFound: true);
        m_Land_parry = m_Land.FindAction("parry", throwIfNotFound: true);
        m_Land_chargeAtk = m_Land.FindAction("chargeAtk", throwIfNotFound: true);
        m_Land_interact = m_Land.FindAction("interact", throwIfNotFound: true);
        m_Land_dialogue = m_Land.FindAction("dialogue", throwIfNotFound: true);
        m_Land_start = m_Land.FindAction("start", throwIfNotFound: true);
        m_Land_select = m_Land.FindAction("select", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Land
    private readonly InputActionMap m_Land;
    private ILandActions m_LandActionsCallbackInterface;
    private readonly InputAction m_Land_move;
    private readonly InputAction m_Land_Jump;
    private readonly InputAction m_Land_vert;
    private readonly InputAction m_Land_dash;
    private readonly InputAction m_Land_atk;
    private readonly InputAction m_Land_cure;
    private readonly InputAction m_Land_whell;
    private readonly InputAction m_Land_spell;
    private readonly InputAction m_Land_ulti;
    private readonly InputAction m_Land_parry;
    private readonly InputAction m_Land_chargeAtk;
    private readonly InputAction m_Land_interact;
    private readonly InputAction m_Land_dialogue;
    private readonly InputAction m_Land_start;
    private readonly InputAction m_Land_select;
    public struct LandActions
    {
        private @NewPlayerScript m_Wrapper;
        public LandActions(@NewPlayerScript wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m_Land_move;
        public InputAction @Jump => m_Wrapper.m_Land_Jump;
        public InputAction @vert => m_Wrapper.m_Land_vert;
        public InputAction @dash => m_Wrapper.m_Land_dash;
        public InputAction @atk => m_Wrapper.m_Land_atk;
        public InputAction @cure => m_Wrapper.m_Land_cure;
        public InputAction @whell => m_Wrapper.m_Land_whell;
        public InputAction @spell => m_Wrapper.m_Land_spell;
        public InputAction @ulti => m_Wrapper.m_Land_ulti;
        public InputAction @parry => m_Wrapper.m_Land_parry;
        public InputAction @chargeAtk => m_Wrapper.m_Land_chargeAtk;
        public InputAction @interact => m_Wrapper.m_Land_interact;
        public InputAction @dialogue => m_Wrapper.m_Land_dialogue;
        public InputAction @start => m_Wrapper.m_Land_start;
        public InputAction @select => m_Wrapper.m_Land_select;
        public InputActionMap Get() { return m_Wrapper.m_Land; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LandActions set) { return set.Get(); }
        public void SetCallbacks(ILandActions instance)
        {
            if (m_Wrapper.m_LandActionsCallbackInterface != null)
            {
                @move.started -= m_Wrapper.m_LandActionsCallbackInterface.OnMove;
                @move.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnMove;
                @move.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_LandActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnJump;
                @vert.started -= m_Wrapper.m_LandActionsCallbackInterface.OnVert;
                @vert.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnVert;
                @vert.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnVert;
                @dash.started -= m_Wrapper.m_LandActionsCallbackInterface.OnDash;
                @dash.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnDash;
                @dash.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnDash;
                @atk.started -= m_Wrapper.m_LandActionsCallbackInterface.OnAtk;
                @atk.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnAtk;
                @atk.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnAtk;
                @cure.started -= m_Wrapper.m_LandActionsCallbackInterface.OnCure;
                @cure.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnCure;
                @cure.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnCure;
                @whell.started -= m_Wrapper.m_LandActionsCallbackInterface.OnWhell;
                @whell.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnWhell;
                @whell.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnWhell;
                @spell.started -= m_Wrapper.m_LandActionsCallbackInterface.OnSpell;
                @spell.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnSpell;
                @spell.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnSpell;
                @ulti.started -= m_Wrapper.m_LandActionsCallbackInterface.OnUlti;
                @ulti.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnUlti;
                @ulti.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnUlti;
                @parry.started -= m_Wrapper.m_LandActionsCallbackInterface.OnParry;
                @parry.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnParry;
                @parry.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnParry;
                @chargeAtk.started -= m_Wrapper.m_LandActionsCallbackInterface.OnChargeAtk;
                @chargeAtk.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnChargeAtk;
                @chargeAtk.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnChargeAtk;
                @interact.started -= m_Wrapper.m_LandActionsCallbackInterface.OnInteract;
                @interact.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnInteract;
                @interact.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnInteract;
                @dialogue.started -= m_Wrapper.m_LandActionsCallbackInterface.OnDialogue;
                @dialogue.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnDialogue;
                @dialogue.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnDialogue;
                @start.started -= m_Wrapper.m_LandActionsCallbackInterface.OnStart;
                @start.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnStart;
                @start.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnStart;
                @select.started -= m_Wrapper.m_LandActionsCallbackInterface.OnSelect;
                @select.performed -= m_Wrapper.m_LandActionsCallbackInterface.OnSelect;
                @select.canceled -= m_Wrapper.m_LandActionsCallbackInterface.OnSelect;
            }
            m_Wrapper.m_LandActionsCallbackInterface = instance;
            if (instance != null)
            {
                @move.started += instance.OnMove;
                @move.performed += instance.OnMove;
                @move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @vert.started += instance.OnVert;
                @vert.performed += instance.OnVert;
                @vert.canceled += instance.OnVert;
                @dash.started += instance.OnDash;
                @dash.performed += instance.OnDash;
                @dash.canceled += instance.OnDash;
                @atk.started += instance.OnAtk;
                @atk.performed += instance.OnAtk;
                @atk.canceled += instance.OnAtk;
                @cure.started += instance.OnCure;
                @cure.performed += instance.OnCure;
                @cure.canceled += instance.OnCure;
                @whell.started += instance.OnWhell;
                @whell.performed += instance.OnWhell;
                @whell.canceled += instance.OnWhell;
                @spell.started += instance.OnSpell;
                @spell.performed += instance.OnSpell;
                @spell.canceled += instance.OnSpell;
                @ulti.started += instance.OnUlti;
                @ulti.performed += instance.OnUlti;
                @ulti.canceled += instance.OnUlti;
                @parry.started += instance.OnParry;
                @parry.performed += instance.OnParry;
                @parry.canceled += instance.OnParry;
                @chargeAtk.started += instance.OnChargeAtk;
                @chargeAtk.performed += instance.OnChargeAtk;
                @chargeAtk.canceled += instance.OnChargeAtk;
                @interact.started += instance.OnInteract;
                @interact.performed += instance.OnInteract;
                @interact.canceled += instance.OnInteract;
                @dialogue.started += instance.OnDialogue;
                @dialogue.performed += instance.OnDialogue;
                @dialogue.canceled += instance.OnDialogue;
                @start.started += instance.OnStart;
                @start.performed += instance.OnStart;
                @start.canceled += instance.OnStart;
                @select.started += instance.OnSelect;
                @select.performed += instance.OnSelect;
                @select.canceled += instance.OnSelect;
            }
        }
    }
    public LandActions @Land => new LandActions(this);
    public interface ILandActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnVert(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnAtk(InputAction.CallbackContext context);
        void OnCure(InputAction.CallbackContext context);
        void OnWhell(InputAction.CallbackContext context);
        void OnSpell(InputAction.CallbackContext context);
        void OnUlti(InputAction.CallbackContext context);
        void OnParry(InputAction.CallbackContext context);
        void OnChargeAtk(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnDialogue(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
}
